### ISSUE TITLE
Namespace Error

### ISSUE THREAD

**Issue by waqar1world** [dmbfm/unity-ar-gps-location-mapbox-route-sample#2]
![Capture](https://user-images.githubusercontent.com/10229929/153718046-6aaf8ec9-7e1b-41f1-9bed-fe759a3a8db9.PNG)
I'm having an issue when I open the project. Getting several namespace errors. imported the AR+GPS Location asset into the project as per your instruction and followed all steps. I'm using Unity 2020.3.28f1.

Any advice with this?

**Comment by dmbfm** [comment]
I am guessing you imported an older version of the AR+GPS location asset. Import the latest version and these errors should go away.

**Comment by waqar1world** [comment]
Version: AR GPS Location v3.5.1

**Comment by dmbfm** [comment]
You need a version newer than v3.6 to use the navigation feature. Just import the latest version from the asset store.

**Comment by waqar1world** [comment]
ok thanks
