### ISSUE TITLE
 Error NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by denverxyz** [dmbfm/unity-ar-gps-location-mapbox-route-sample#5]
Help when I try to run the app it show : 

NullReferenceException: Object reference not set to an instance of an object
Mapbox.Unity.MeshGeneration.Modifiers.ModifierStack.Initialize () (at Assets/Mapbox/Unity/MeshGeneration/Modifiers/ModifierStack.cs:115)
Mapbox.Unity.MeshGeneration.Interfaces.VectorLayerVisualizer.Initialize () (at Assets/Mapbox/Unity/MeshGeneration/LayerVisualizers/VectorLayerVisualizer.cs:462)
Mapbox.Unity.MeshGeneration.Factories.VectorTileFactory.AddVectorLayerVisualizer (Mapbox.Unity.Map.VectorSubLayerProperties subLayer) (at Assets/Mapbox/Unity/MeshGeneration/Factories/VectorTileFactory.cs:102)
Mapbox.Unity.MeshGeneration.Factories.VectorTileFactory.CreateLayerVisualizers () (at Assets/Mapbox/Unity/MeshGeneration/Factories/VectorTileFactory.cs:497)
Mapbox.Unity.MeshGeneration.Factories.VectorTileFactory.OnInitialized () (at Assets/Mapbox/Unity/MeshGeneration/Factories/VectorTileFactory.cs:190)
Mapbox.Unity.MeshGeneration.Factories.AbstractTileFactory.Initialize (Mapbox.Platform.IFileSource fileSource) (at Assets/Mapbox/Unity/MeshGeneration/Factories/AbstractTileFactory.cs:66)
Mapbox.Unity.Map.AbstractMapVisualizer.Initialize (Mapbox.Unity.Map.Interfaces.IMapReadable map, Mapbox.Platform.IFileSource fileSource) (at Assets/Mapbox/Unity/Map/AbstractMapVisualizer.cs:97)
Mapbox.Unity.Map.AbstractMap.InitializeMap (Mapbox.Unity.Map.MapOptions options) (at Assets/Mapbox/Unity/Map/AbstractMap.cs:769)
Mapbox.Unity.Map.AbstractMap.SetUpMap () (at Assets/Mapbox/Unity/Map/AbstractMap.cs:651)
Mapbox.Unity.Map.AbstractMap.MapOnStartRoutine (System.Boolean coroutine) (at Assets/Mapbox/Unity/Map/AbstractMap.cs:538)
Mapbox.Unity.Map.AbstractMap.Start () (at Assets/Mapbox/Unity/Map/AbstractMap.cs:500)

**Comment by dmbfm** [comment]
Could you send me your project folder in a .zip file to daniel.mbfm@gmail.com so I can take a look at it? Thanks

**Comment by denverxyz** [comment]
unity-ar-gps-location-mapbox-route-sample.zip
<https://drive.google.com/file/d/144tqpU7RPu5lWmCl4K1uENJK4y2afsXu/view?usp=drive_web>
this is the project...

And 1 more question if this project would compile, can i add custom marker
on the mapbox using this project

**Comment by dmbfm** [comment]
I believe the issue is fixed by now. could you try the latest main branch?

>And 1 more question if this project would compile, can i add custom marker
>on the mapbox using this project
Sure, I you just change the 3d model on the scene I believe

**Comment by denverxyz** [comment]
thank you for your reply, i have now able to compile and run on android.
Unfortunately, the apps ask permission for gps only, not camera and other
permissions. So, the camera for AR navigation not showing in the app. the
demo apps shown below. Where is the real location for Android Manifest.xml

[image: image.png]

**Comment by denverxyz** [comment]
Actually the issue was im not configuring on Player Setting Configuration. Thanks you for helping me on the Email. thank you ya
