### ISSUE TITLE
the Directions Label is not displayed (the "Custom-routes" branch)

### ISSUE THREAD

**Issue by tisimheeg** [dmbfm/unity-ar-gps-location-mapbox-route-sample#6]
For some reason, when playing the scene, the Directions Label (the "Custom-routes" branch) is not displayed. TxtMeshPro and all required assets are imported. No errors are displayed in the Unity console.

![2022-08-01_22-08-38](https://user-images.githubusercontent.com/110419810/182227258-393371fb-11a9-4c65-b08c-8ac4546c4a83.png)

**Comment by dmbfm** [comment]
This only happens in the custom routes branch?

**Comment by tisimheeg** [comment]
Yes. In the scene of the Main branch, the the Directions Label is displayed well.
